name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    
    permissions:
      id-token: write
      contents: read
      
    steps:
      - uses: actions/checkout@v4

      - name: Create app package
        run: |      
          zip -jr miapp.zip miapp

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configurar conexion para despliegue en AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.DEPLOY_ROLE }}
          aws-region: us-east-1

      - name: Terraform init
        working-directory: infraestructure
        run: terraform init -input=false

      - name: Terraform apply
        working-directory: infraestructure
        run: terraform apply -auto-approve -input=false