name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  tests-and-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        run: pip install pytest boto3 flake8 flask flask_wtf coverage

      - name: Lint (flake8)
        working-directory: ./miapp
        run: flake8 app.py -v

      - name: Tests with coverage
        run: |
          coverage run -m pytest -q tests
          coverage xml
            
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v1
        env:
          SONAR_HOST_URL: https://sonarcloud.io
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: .
          args: >
            -Dsonar.projectKey=tu_org_tu_proyecto
            -Dsonar.organization=tu_org
            -Dsonar.sources=miapp
            -Dsonar.python.coverage.reportPaths=coverage.xml

      
      
      # - name: Install dependencies
      #   run: |
      #     pip install pytest flake8

      # - name: Run tests
      #   run: |
      #     pytest

      # - name: Run flake8
      #   run: |
      #     source .venv/bin/activate
      #     flake8 app tests